version: 1.4.0.{build}
pull_requests:
  do_not_increment_build_number: true
clone_depth: 1
install:
- cmd: >-
    set PATH=C:\Ruby22\bin;%PATH%

    bundle install

    bundle exec rake appveyor
cache: packages -> **\packages.config
build: off
test_script:
- cmd: bundle exec rake tests
artifacts:
- path: '**\Build\appveyor_artifacts\ModulusChecker.1.3.1.nupkg'
  name: nuget_artifact
deploy: off
# on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))